---
#dependency:
#  name: galaxy
#  options:
#    requirements-file: collections.yml
driver:
  name: default
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman
platforms:
  - name: instance
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    image: quay.io/rockylinux/rockylinux:9.4
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: $MOLECULE_PROJECT_DIRECTORY/..
