name: Ansible Role CI
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main]

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Red Hat container registry
        run: |
          podman login registry.redhat.io -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Run ansible-lint in podman container
        run: |
          podman run --rm \
            -v $PWD:/workdir:Z \
            -w /workdir \
            registry.redhat.io/ansible-automation-platform-25/ansible-dev-tools-rhel8:25.2.0-18 \
            ansible-lint

  unit-test:
    needs: lint
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Red Hat container registry
        run: |
          podman login registry.redhat.io -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Run ansible-lint in podman container
        run: |
          podman run --rm \
            -v $PWD:/workdir/roles/setup:Z \
            -w /workdir/roles/setup \
            --privileged \
            -v $XDG_RUNTIME_DIR/podman/podman.sock:/run/podman/podman.sock:Z \
            -e CONTAINER_HOST=unix://run/podman/podman.sock \
            --userns=keep-id \
            registry.redhat.io/ansible-automation-platform-25/ansible-dev-tools-rhel8:25.2.0-18 \
            molecule test
